// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TAS.Data;

#nullable disable

namespace TAS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251007042222_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TAS.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 10, 7, 11, 22, 21, 539, DateTimeKind.Local).AddTicks(5353),
                            Description = "Laptop cao cấp",
                            Name = "Laptop Dell",
                            Price = 15000000m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 10, 7, 11, 22, 21, 539, DateTimeKind.Local).AddTicks(5368),
                            Description = "Điện thoại thông minh",
                            Name = "iPhone 15",
                            Price = 25000000m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 10, 7, 11, 22, 21, 539, DateTimeKind.Local).AddTicks(5372),
                            Description = "Tivi 55 inch",
                            Name = "Samsung TV",
                            Price = 12000000m,
                            Stock = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
